//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseWork2
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product_address()
        {
            this.cheque_set = new HashSet<cheque_set>();
        }
    
        public int product_address_id { get; set; }
        public int product_size_id { get; set; }
        public int store_address_id { get; set; }
        public Nullable<int> store_product_amount { get; set; }
        public System.DateTime change_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cheque_set> cheque_set { get; set; }
        public virtual product_size product_size { get; set; }
        public virtual store_address store_address { get; set; }
    }
}
