//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice2.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class cswEntities : DbContext
    {
        public cswEntities()
            : base("name=cswEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cheque_set> cheque_set { get; set; }
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<dict_category> dict_category { get; set; }
        public virtual DbSet<dict_city> dict_city { get; set; }
        public virtual DbSet<dict_product_status> dict_product_status { get; set; }
        public virtual DbSet<dict_size> dict_size { get; set; }
        public virtual DbSet<price> price { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<product_address> product_address { get; set; }
        public virtual DbSet<status_of_cheque> status_of_cheque { get; set; }
        public virtual DbSet<store> store { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    
        public virtual ObjectResult<GetBySearch_Result> GetBySearch(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetBySearch_Result>("GetBySearch", searchParameter);
        }
    
        public virtual int GetCustBag(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetCustBag", cust_idParameter);
        }
    
        public virtual ObjectResult<GetCustOrder_Result> GetCustOrder(Nullable<int> cust_id)
        {
            var cust_idParameter = cust_id.HasValue ?
                new ObjectParameter("cust_id", cust_id) :
                new ObjectParameter("cust_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetCustOrder_Result>("GetCustOrder", cust_idParameter);
        }
    
        public virtual int GetLastAmount(Nullable<int> store_id, Nullable<int> product_size_id)
        {
            var store_idParameter = store_id.HasValue ?
                new ObjectParameter("store_id", store_id) :
                new ObjectParameter("store_id", typeof(int));
    
            var product_size_idParameter = product_size_id.HasValue ?
                new ObjectParameter("product_size_id", product_size_id) :
                new ObjectParameter("product_size_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetLastAmount", store_idParameter, product_size_idParameter);
        }
    
        public virtual int GetLastPrice(Nullable<int> product_id)
        {
            var product_idParameter = product_id.HasValue ?
                new ObjectParameter("product_id", product_id) :
                new ObjectParameter("product_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetLastPrice", product_idParameter);
        }
    
        public virtual int GetStats(Nullable<int> store_id, Nullable<System.DateTime> date_one, Nullable<System.DateTime> date_two)
        {
            var store_idParameter = store_id.HasValue ?
                new ObjectParameter("store_id", store_id) :
                new ObjectParameter("store_id", typeof(int));
    
            var date_oneParameter = date_one.HasValue ?
                new ObjectParameter("date_one", date_one) :
                new ObjectParameter("date_one", typeof(System.DateTime));
    
            var date_twoParameter = date_two.HasValue ?
                new ObjectParameter("date_two", date_two) :
                new ObjectParameter("date_two", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetStats", store_idParameter, date_oneParameter, date_twoParameter);
        }
    
        public virtual ObjectResult<OrderStatus_NoFilters_Result> OrderStatus_NoFilters(Nullable<int> store_id)
        {
            var store_idParameter = store_id.HasValue ?
                new ObjectParameter("store_id", store_id) :
                new ObjectParameter("store_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OrderStatus_NoFilters_Result>("OrderStatus_NoFilters", store_idParameter);
        }
    }
}
