//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class price
    {
        public int price_version_id { get; set; }
        public int product_id { get; set; }
        public Nullable<decimal> product_price { get; set; }
        public System.DateTime version_date { get; set; }
        public string price_comment { get; set; }
    
        public virtual product product { get; set; }
    }
}
