//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyPlanWeb.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses
    {
        public int Id { get; set; }
        public int Counter { get; set; }
        public int DirectionId { get; set; }
    
        public virtual Directions Directions { get; set; }
        public virtual StudySubjects StudySubjects { get; set; }
    }
}
