//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyPlanWeb.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupStudySubjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupStudySubjects()
        {
            this.StudyTasks = new HashSet<StudyTasks>();
        }
    
        public int Id { get; set; }
        public int GroupId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<int> StudySubjectId { get; set; }
    
        public virtual Groups Groups { get; set; }
        public virtual StudySubjects StudySubjects { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudyTasks> StudyTasks { get; set; }
    }
}
