//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyPlanWeb.Schema
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlanEntities : DbContext
    {
        public PlanEntities()
            : base("name=PlanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<Directions> Directions { get; set; }
        public virtual DbSet<Groups> Groups { get; set; }
        public virtual DbSet<GroupStudySubjects> GroupStudySubjects { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<StudySubjects> StudySubjects { get; set; }
        public virtual DbSet<StudyTasks> StudyTasks { get; set; }
        public virtual DbSet<Subjects> Subjects { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TaskRatings> TaskRatings { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
