//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyPlanWeb.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudySubjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudySubjects()
        {
            this.GroupStudySubjects = new HashSet<GroupStudySubjects>();
        }
    
        public int Id { get; set; }
        public int CourseId { get; set; }
        public int SubjectId { get; set; }
    
        public virtual Courses Courses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupStudySubjects> GroupStudySubjects { get; set; }
        public virtual Subjects Subjects { get; set; }
    }
}
