//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyPlanWeb.Schema
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskRatings
    {
        public int Id { get; set; }
        public int Rating { get; set; }
        public int StudentId { get; set; }
        public int StudyTaskId { get; set; }
    
        public virtual Students Students { get; set; }
        public virtual StudyTasks StudyTasks { get; set; }
    }
}
