//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice2
{
    using System;
    using System.Collections.Generic;
    
    public partial class status_of_cheque
    {
        public int status_cheque_id { get; set; }
        public int cheque_prod_id { get; set; }
        public int cheque_status_id { get; set; }
        public System.DateTime status_date { get; set; }
    
        public virtual cheque_product_status cheque_product_status { get; set; }
        public virtual cheque_set cheque_set { get; set; }
    }
}
